/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crosswalkproject_sample_Echo */

#ifndef _Included_org_crosswalkproject_sample_Echo
#define _Included_org_crosswalkproject_sample_Echo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crosswalkproject_sample_Echo
 * Method:    messageFromNativeCode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_crosswalkproject_sample_Echo_messageFromNativeCode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
